name: Release preparation

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-preparation:
    name: Release preparation & PR creation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Update version
        id: version-update
        uses: TriPSs/conventional-changelog-action@v5.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-message: "chore(release): {version}"
          tag-prefix: ""
          version-file: pyproject.toml
          version-path: tool.poetry.version
          create-summary: true
          skip-ci: false
          skip-on-empty: false
          output-file: true
          git-push: false

      - name: missing version output
        if: ${{ !steps.version-update.outputs.version }}
        run: >
          echo "ERROR: Version output is missing from the previous step!" && exit 1

      - name: Create Pull Request on dev
        uses: peter-evans/create-pull-request@v6.1.0
        id: cpr-dev
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: pre-release-${{ steps.version-update.outputs.version }}
          base: dev
          title: "chore: update version to ${{ steps.version-update.outputs.version }} on dev"
          body: ">To keep the version on dev branch up-to-date, this PR should be merged while merging dev into the main branch in the following PR.\n\nThis is an automatic PR created by github actions.\nClose and delete branch in case it is not needed."
          assignees: geode-main
          reviewers: geode-main

      - name: Create Pull Request for release
        uses: peter-evans/create-pull-request@v6.1.0
        if: ${{ steps.cpr-dev.outputs.pull-request-number }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: pre-release-${{ steps.version-update.outputs.version }}
          base: main
          title: "chore(release): ${{ steps.version-update.outputs.version }}"
          body: ">Pull request #${{ steps.cpr-dev.outputs.pull-request-number }} should be merged to keep version updated.\n\nThis is an automatic PR created by github actions.\nClose and delete branch in case it is not needed."
          assignees: geode-main
          reviewers: geode-main